spring:
  profile.active: prod
  datasource:
    url: ${DATASOURCE_URL_FORO}
    username: ${DATASOURCE_USERNAME}
    password: ${DATASOURCE_PASSWORD}
  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true

server:
  error:
    include-stacktrace: never
api:
  security:
    secret: ${JWT_SECRET}


